import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { LeftSideBar } from "../../components/shared/LeftSideBar";
import { MobileNav } from "../../components/shared/MobileNav";
import { Nav } from "../../components/shared/Nav";
import { RightSideBar } from "../../components/shared/RightSideBar";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Nav />
                <main className="flex flex-row">
                    <LeftSideBar />
                    <section className="main-container">
                        <div className="w-full max-w-4xl">
                            {children}
                        </div>
                    </section>
                    <RightSideBar />
                </main>
                <MobileNav />
            </body>
        </html>
    );
}
